# Makefile for autospec
# Copyright (C) 2008,2012 by Davide Madrisan <davide.madrisan@gmail.com>

# This program is free software; you can redistribute it and/or modify it under
# the terms of version 2 of the GNU General Public License as published by the
# Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY, to the extent permitted by law; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along  with
# this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.

prefix = /usr/local
sysconfdir = /etc
tmpdir = /tmp
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
confdir = $(sysconfdir)/autospec.d
datadir = $(prefix)/share
libdir = $(datadir)/autospec/lib
localedir = $(datadir)/locale
mandir = $(datadir)/man
#plugindir = $(datadir)/autospec/plugins
plugindir = $(bindir)
templatedir = $(datadir)/autospec/templates
testdir = $(datadir)/autospec/tests
tooldir = $(bindir)

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} -m 755
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_DIR = ${INSTALL} -d -m 755

PO_COPYRIGH_HOLDER = Davide Madrisan
PO_BUGS_ADDRESS = davide.madrisan@gmail.com